// Code generated by hertz generator.

package main

import (
	"fmt"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/zhikongming/stock/biz/config"
	"github.com/zhikongming/stock/biz/dal"
)

func main() {

	config.InitConfig()
	conf := config.GetConfig()
	// 初始化配置
	dal.InitMysql(conf)

	h := server.Default(
		server.WithHostPorts(fmt.Sprintf(":%d", conf.Server.Port)),
	)

	register(h)
	h.Spin()
}
