// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/zhikongming/stock/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.POST("/task/stock/code", handler.SyncStockCode)
	r.POST("/analyze/stock/code", handler.AnalyzeStockCode)
	r.POST("/filter/stock/code", handler.FilterStockCode)
}
