DB:
  host: "localhost"
  port: 3306
  user: "stock"
  password: "stock_zw_zzy_01"
  dbname: "stock_agent"
Server:
  port: 7112
Replace:
  origin_domain: "localhost:6789"
  replaced_domain: "115.190.101.171:7112"